/*
 * DSS - Digital Signature Services
 *
 * Copyright (C) 2011 European Commission, Directorate-General Internal Market and Services (DG MARKT), B-1049 Bruxelles/Brussel
 *
 * Developed by: 2011 ARHS Developments S.A. (rue Nicolas Bové 2B, L-1253 Luxembourg) http://www.arhs-developments.com
 *
 * This file is part of the "DSS - Digital Signature Services" project.
 *
 * "DSS - Digital Signature Services" is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the
 * License, or (at your option) any later version.
 *
 * DSS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with
 * "DSS - Digital Signature Services".  If not, see <http://www.gnu.org/licenses/>.
 */

package eu.europa.ec.markt.dss.applet;

import eu.europa.ec.markt.dss.applet.model.SignatureWizardModel;
import eu.europa.ec.markt.dss.applet.model.WizardUsage;
import eu.europa.ec.markt.dss.applet.wizard.AbstractWizardPanel;
import eu.europa.ec.markt.dss.signature.SignaturePackaging;

import java.io.File;

import javax.swing.JFileChooser;

/**
 * Let the user choose the destination file.
 * 
 *
 * @version $Revision: 1867 $ - $Date: 2013-04-08 13:44:56 +0200 (Mon, 08 Apr 2013) $
 */

@SuppressWarnings("serial")
public class SaveDocumentPanel extends AbstractWizardPanel {

    public static final String ID = "SAVE_DOCUMENT";
    private SignatureWizardModel model;
    private JFileChooser jFileChooser1;
    private File choosedFile;

    /** Creates new form SaveDocumentPanel */
    public SaveDocumentPanel(SignatureWizardModel signatureWizardModel) {

        this.model = signatureWizardModel;

        initComponents();

        jFileChooser1 = new JFileChooser();
    }

    @Override
    public Object getPanelDescriptorIdentifier() {
        return ID;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        filename = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("eu/europa/ec/markt/dss/applet/i18n"); // NOI18N
        jLabel1.setText(bundle.getString("SAVE_TO_FILE")); // NOI18N

        jButton1.setText(bundle.getString("CHOOSE_DESTINATION")); // NOI18N
        jButton1.setName("choose_destination"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        filename.setEditable(false);
        filename.setText("jTextField1");
        filename.setBorder(null);
        filename.setName("save_path"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filename, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                    .addComponent(jButton1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(filename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(196, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

        int result = jFileChooser1.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            choosedFile = jFileChooser1.getSelectedFile();
            filename.setText(choosedFile.getAbsolutePath());
        }

    }// GEN-LAST:event_jButton1ActionPerformed

    @Override
    public Object getNextPanelDescriptor() {
        return WizardFinishedPanel.ID;
    }

    @Override
    public Object getBackPanelDescriptor() {
        switch (model.getWizardUsage()) {
        case SIGN:
            return PersonalDataPanel.ID;
        case EXTEND:
            return ChooseSignaturePanel.ID;
        default:
            return null;
        }
    }

    /*
     * (non-Javadoc)
     * 
     * @see eu.europa.ec.markt.dss.applet.wizard.WizardPanel#aboutToDisplayPanel()
     */
    @Override
    public void aboutToDisplayPanel() {

        String originalName = null; 
        File parentDir = null;
        
        switch (model.getWizardUsage()) {
        case SIGN:
            getWizard().setStepsProgression(7);
            originalName = model.getOriginalFile().getName();
            parentDir = model.getOriginalFile().getParentFile();
            break;
        case EXTEND:
            getWizard().setStepsProgression(3);
            originalName = model.getSignedFile().getName();
            parentDir = model.getSignedFile().getParentFile();
            break;
        }

        String originalExtension = null;
        int i2 = originalName.lastIndexOf(".");
        if (i2 > 0) {
            originalExtension = originalName.substring(i2);
            originalName = originalName.substring(0, i2);
        }

        String newName = null;
        if (model.getWizardUsage() == WizardUsage.EXTEND) {
            newName = originalName + "-extended" + originalExtension;
        } else if (model.getPackaging() == SignaturePackaging.ENVELOPING
                && model.getSignatureFormat().startsWith("XAdES")) {
            newName = originalName + "-signed" + ".xml";
        } else if (model.getPackaging() == SignaturePackaging.DETACHED
                && model.getSignatureFormat().startsWith("XAdES")) {
            newName = originalName + "-signed" + ".xml";
        } else if (model.getSignatureFormat().startsWith("CAdES-")
                && !model.getOriginalFile().getName().endsWith(".p7m")) {
            newName = model.getOriginalFile().getName() + ".p7m";
        } else if (model.getSignatureFormat().startsWith("ASiC-")) {
            newName = model.getOriginalFile().getName() + ".asics";
        } else {
            int i = model.getOriginalFile().getName().lastIndexOf(".");
            if (i > 0) {
                newName = model.getOriginalFile().getName().substring(0, i) + "-signed"
                        + model.getOriginalFile().getName().substring(i);
            } else {
                newName = model.getOriginalFile().getName() + "-signed";
            }
        }

        choosedFile = new File(parentDir.getParentFile(), newName);

        jFileChooser1.setCurrentDirectory(choosedFile.getParentFile());
        jFileChooser1.setSelectedFile(choosedFile);

        filename.setText(choosedFile.getAbsolutePath());

    }

    @Override
    public void aboutToHidePanel() {
        switch(model.getWizardUsage()) {
        case SIGN:
            model.setSignedFile(jFileChooser1.getSelectedFile());
            break;
        case EXTEND: 
            model.setExtendedFile(jFileChooser1.getSelectedFile());
            break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField filename;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
