/*
 * DSS - Digital Signature Services
 *
 * Copyright (C) 2011 European Commission, Directorate-General Internal Market and Services (DG MARKT), B-1049 Bruxelles/Brussel
 *
 * Developed by: 2011 ARHS Developments S.A. (rue Nicolas Bové 2B, L-1253 Luxembourg) http://www.arhs-developments.com
 *
 * This file is part of the "DSS - Digital Signature Services" project.
 *
 * "DSS - Digital Signature Services" is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the
 * License, or (at your option) any later version.
 *
 * DSS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with
 * "DSS - Digital Signature Services".  If not, see <http://www.gnu.org/licenses/>.
 */

package eu.europa.ec.markt.dss.applet;

import eu.europa.ec.markt.dss.applet.wizard.WizardSteps;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;

/**
 * 
 * Display the progress in a signing wizard
 * 
 *
 * @version $Revision: 1867 $ - $Date: 2013-04-08 13:44:56 +0200 (Mon, 08 Apr 2013) $
 */

public class WizardStepsSign extends javax.swing.JPanel implements WizardSteps {

    /** Creates new form WizardSteps */
    public WizardStepsSign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setMaximumSize(new java.awt.Dimension(400, 32767));
        setMinimumSize(new java.awt.Dimension(400, 90));
        setLayout(new java.awt.GridLayout(1, 7));

        jLabel14.setText("1");
        jLabel14.setPreferredSize(new java.awt.Dimension(10, 11));
        jPanel1.add(jLabel14);

        add(jPanel1);

        jLabel15.setText("2");
        jLabel15.setPreferredSize(new java.awt.Dimension(10, 11));
        jPanel2.add(jLabel15);

        add(jPanel2);

        jLabel16.setText("3");
        jLabel16.setPreferredSize(new java.awt.Dimension(10, 11));
        jPanel3.add(jLabel16);

        add(jPanel3);

        jLabel17.setText("4");
        jLabel17.setPreferredSize(new java.awt.Dimension(10, 11));
        jPanel4.add(jLabel17);

        add(jPanel4);

        jLabel18.setText("5");
        jLabel18.setPreferredSize(new java.awt.Dimension(10, 11));
        jPanel5.add(jLabel18);

        add(jPanel5);

        jLabel19.setText("6");
        jLabel19.setPreferredSize(new java.awt.Dimension(10, 11));
        jPanel6.add(jLabel19);

        add(jPanel6);

        jLabel1.setText("7");
        jLabel1.setPreferredSize(new java.awt.Dimension(10, 11));
        jPanel7.add(jLabel1);

        add(jPanel7);
    }// </editor-fold>//GEN-END:initComponents

    private void setColorOnPanelList(final Color color, final Component... comps) {
        for (Component p : comps) {
            p.setBackground(color);
            p.repaint();
        }
    }

    private int currentStep = 0;

    /*
     * (non-Javadoc)
     * 
     * @see javax.swing.JComponent#paint(java.awt.Graphics)
     */
    @Override
    public void paint(Graphics g) {
        Color blue = new Color(0x99, 0xCC, 0xFF);
        switch (this.currentStep) {
        case 1:
            setColorOnPanelList(blue, jPanel1);
            break;
        case 2:
            setColorOnPanelList(blue, jPanel2);
            break;
        case 3:
            setColorOnPanelList(blue, jPanel3);
            break;
        case 4:
            setColorOnPanelList(blue, jPanel4);
            break;
        case 5:
            setColorOnPanelList(blue, jPanel5);
            break;
        case 6:
            setColorOnPanelList(blue, jPanel6);
            break;
        case 7:
            setColorOnPanelList(blue, jPanel7);
            break;
        }
        super.paint(g);
    }

    /*
     * (non-Javadoc)
     * 
     * @see eu.europa.ec.markt.dss.applet.WizardSteps#setCurrentStep(int)
     */
    @Override
    public void setCurrentStep(int step) {
        this.currentStep = step;
        setColorOnPanelList(new Color(240, 240, 240), jPanel1, jPanel2, jPanel3, jPanel4, jPanel5, jPanel6, jPanel7);
        repaint();
        if (getParent() != null) {
            getParent().repaint();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables

}
